version: "3"

services:
  selenium:
    image: 'selenium/standalone-chrome'

  app:
    build: 'https://github.com/siraj-ai/uk-tier-2-companies.git'
    command: 'node index.js'
    links:
      - selenium
    depends_on:
      - selenium
