version: "3"

services:
  selenium:
    image: 'selenium/standalone-chrome'

  app:
    image: 'sirajfarhan/uk-tier-2-companies'
    command: 'node index.js'
    links:
      - selenium
    depends_on:
      - selenium
