version: "3"

services:
  selenium:
    image: 'selenium/standalone-chrome'

  proxy_manager:
    image: 'luminati/luminati-proxy'
    command: 'luminati'

  proxy_setup:
    build: 'https://github.com/siraj-ai/luminati_proxy_setup.git'
    command: 'node index.js'
    depends_on:
      - proxy_manager

  app:
    build: 'https://github.com/siraj-ai/uk-tier-2-companies.git'
    command: 'node index.js'
    depends_on:
      - selenium
      - proxy_setup
