version: "3"

services:
  selenium:
    image: 'selenium/standalone-chrome'

  luminati:
    image: 'luminati/luminati-proxy'
    command: 'luminati'
    ports:
    - 8000:22999

  proxy_setup:
    build: 'https://github.com/siraj-ai/luminati_proxy_setup.git'
    command: 'node index.js'
    links:
      - luminati
    depends_on:
      - luminati

  app:
    build: 'https://github.com/siraj-ai/uk-tier-2-companies.git'
    command: 'node index.js'
    links:
      - luminati
      - selenium
    depends_on:
      - proxy_setup
