version: "3"

services:
  selenium:
    image: 'selenium/standalone-chrome'

  luminati:
    image: 'luminati'
    command: 'luminati --ssl true'

  luminati_proxy_setup:
    image: 'sirajfarhan/luminati_proxy_setup'
    links:
      - luminati
    depends_on:
      - luminati

  app:
    image: 'sirajfarhan/uk-tier-2-companies'
    command: 'node index.js'
    links:
      - selenium
      - luminati
    depends_on:
      - selenium
      - luminati
